/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosjava;

import java.awt.CardLayout;

/**
 *
 * @author USER
 */
public class Banco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Banco.class.getName());

    private java.util.ArrayList<Usuario> listaUsuarios = new java.util.ArrayList<>();

    private Usuario usuarioActual = null;

    /**
     * Creates new form Banco
     */
    public Banco() {
        //Usuarios de BancaMex
        initComponents();
        listaUsuarios.add(new Usuario("Roberto", "123", 5000.00));
        listaUsuarios.add(new Usuario("Luis", "125", 10000.00));

        //Código de escalado de imágenes
        setImagenLabel("/fondo_login.jpg", lblImagenFondo);
        setImagenLabel("/fondo_menu.jpg", lblFondoMenu);
        setImagenLabel("/fondo_registro.jpg", lblFondoRegistro);
        setImagenLabel("/fondo_registro.jpg", lblFondoMenu);
        setImagenLabel("/fondo_retirar.jpg", lblImagenFondoRetiro);
        setImagenLabel("/fondo_retirar.jpg", lblFondoTransferencia);
        setImagenLabel("/fondo_registro.jpg", lblPagoServicios);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCards = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        btnCrearNuevo = new javax.swing.JButton();
        lblTituloBanco = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();
        lblEtiquetaPass = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblEtiquetaPass1 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        txtRegPass = new javax.swing.JPasswordField();
        btnConfirmarRegistro = new javax.swing.JButton();
        btnVolverLogin = new javax.swing.JButton();
        txtRegMonto = new javax.swing.JTextField();
        txtRegUsuario = new javax.swing.JTextField();
        lblRegMonto = new javax.swing.JLabel();
        lblRegPass = new javax.swing.JLabel();
        lblEtiquetaUsuario2 = new javax.swing.JLabel();
        lblTituloRegistro = new javax.swing.JLabel();
        lblFondoRegistro = new javax.swing.JLabel();
        lblRegNombre = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnConsultarSaldo = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnPagoServicio = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        lblBienvenidaMenu = new javax.swing.JLabel();
        lblFondoMenu = new javax.swing.JLabel();
        panelTransferir = new javax.swing.JPanel();
        txtDestinatario = new javax.swing.JTextField();
        txtMontoTransferir = new javax.swing.JTextField();
        btnConfirmarTransferencia = new javax.swing.JButton();
        btnCancelarTransferencia = new javax.swing.JButton();
        lblTransferenciaElectronica = new javax.swing.JLabel();
        lblMontoTransferencia = new javax.swing.JLabel();
        lblNoDestinatario = new javax.swing.JLabel();
        lblFondoTransferencia = new javax.swing.JLabel();
        panelRetirar = new javax.swing.JPanel();
        txtDineroRetir = new javax.swing.JTextField();
        btnRetirar50 = new javax.swing.JButton();
        btnRetirar200 = new javax.swing.JButton();
        btnRetirar500 = new javax.swing.JButton();
        btnRetirar101 = new javax.swing.JButton();
        btnRetirarDinero = new javax.swing.JButton();
        btnVolverRetiro = new javax.swing.JButton();
        lblRetiroDeEfectivo = new javax.swing.JLabel();
        lblDineroRetirar = new javax.swing.JLabel();
        lblRetiroRapido = new javax.swing.JLabel();
        lblSaldoDisponibleRetiro = new javax.swing.JLabel();
        lblImagenFondoRetiro = new javax.swing.JLabel();
        panelPagoServicios = new javax.swing.JPanel();
        lblRetiroDeEfectivo1 = new javax.swing.JLabel();
        lblDineroRetirar1 = new javax.swing.JLabel();
        cbxTipoServicio = new javax.swing.JComboBox<>();
        txtMontoServicio = new javax.swing.JTextField();
        lblDineroRetirar2 = new javax.swing.JLabel();
        btnConfirmarPago = new javax.swing.JButton();
        btnVolverServicios = new javax.swing.JButton();
        lblPagoServicios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCards.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(0, 0, 0));
        panelLogin.setForeground(new java.awt.Color(0, 0, 0));

        txtPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(184, 134, 11));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnRecuperar.setBackground(new java.awt.Color(184, 134, 11));
        btnRecuperar.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRecuperar.setForeground(new java.awt.Color(0, 0, 0));
        btnRecuperar.setText("Recuperar Contraseña");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        btnCrearNuevo.setBackground(new java.awt.Color(184, 134, 11));
        btnCrearNuevo.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnCrearNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearNuevo.setText("Crear Nuevo Usuario");
        btnCrearNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevoActionPerformed(evt);
            }
        });

        lblTituloBanco.setBackground(new java.awt.Color(212, 175, 55));
        lblTituloBanco.setFont(new java.awt.Font("Segoe UI Black", 0, 100)); // NOI18N
        lblTituloBanco.setForeground(new java.awt.Color(212, 175, 55));
        lblTituloBanco.setText("BancoMex");

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_login.jpg"))); // NOI18N

        lblEtiquetaPass.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblEtiquetaPass.setForeground(new java.awt.Color(255, 255, 255));
        lblEtiquetaPass.setText("USUARIO:");

        lblBienvenida.setBackground(new java.awt.Color(212, 175, 55));
        lblBienvenida.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(212, 175, 55));
        lblBienvenida.setText("¡Bienvenido!");

        lblEtiquetaPass1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblEtiquetaPass1.setForeground(new java.awt.Color(255, 255, 255));
        lblEtiquetaPass1.setText("CONTRASEÑA:");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lblBienvenida))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTituloBanco)))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblEtiquetaPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblImagenFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(195, 195, 195)
                    .addComponent(lblEtiquetaPass1)
                    .addContainerGap(2500, Short.MAX_VALUE)))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTituloBanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenida)
                .addGap(18, 18, 18)
                .addComponent(lblEtiquetaPass)
                .addGap(26, 26, 26)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(lblImagenFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(397, 397, 397)
                    .addComponent(lblEtiquetaPass1)
                    .addContainerGap(838, Short.MAX_VALUE)))
        );

        panelCards.add(panelLogin, "card2");

        panelRegistro.setBackground(new java.awt.Color(0, 0, 0));
        panelRegistro.setForeground(new java.awt.Color(0, 0, 0));

        txtRegPass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N

        btnConfirmarRegistro.setBackground(new java.awt.Color(184, 134, 11));
        btnConfirmarRegistro.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        btnConfirmarRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarRegistro.setText("Confirmar");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        btnVolverLogin.setBackground(new java.awt.Color(184, 134, 11));
        btnVolverLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        btnVolverLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverLogin.setText("Volver");
        btnVolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLoginActionPerformed(evt);
            }
        });

        txtRegMonto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtRegMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegMontoActionPerformed(evt);
            }
        });

        txtRegUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtRegUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegUsuarioActionPerformed(evt);
            }
        });

        lblRegMonto.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblRegMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblRegMonto.setText("SALDO:");

        lblRegPass.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblRegPass.setForeground(new java.awt.Color(255, 255, 255));
        lblRegPass.setText("CONTRASEÑA:");

        lblEtiquetaUsuario2.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblEtiquetaUsuario2.setForeground(new java.awt.Color(255, 255, 255));

        lblTituloRegistro.setBackground(new java.awt.Color(212, 175, 55));
        lblTituloRegistro.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblTituloRegistro.setForeground(new java.awt.Color(212, 175, 55));
        lblTituloRegistro.setText("Registrar Nuevo Usuario");

        lblFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_registro.jpg"))); // NOI18N

        lblRegNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblRegNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblRegNombre.setText("NOMBRE:");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEtiquetaUsuario2)
                    .addComponent(lblRegMonto)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnConfirmarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnVolverLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTituloRegistro)
                    .addComponent(lblRegPass)
                    .addComponent(lblRegNombre)
                    .addComponent(txtRegUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFondoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRegistro)
                .addGap(7, 7, 7)
                .addComponent(lblRegNombre)
                .addGap(18, 18, 18)
                .addComponent(txtRegUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegPass)
                .addGap(28, 28, 28)
                .addComponent(txtRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegMonto)
                .addGap(18, 18, 18)
                .addComponent(txtRegMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEtiquetaUsuario2)
                .addGap(45, 649, Short.MAX_VALUE))
            .addComponent(lblFondoRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCards.add(panelRegistro, "card3");

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        btnConsultarSaldo.setBackground(new java.awt.Color(184, 134, 11));
        btnConsultarSaldo.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnConsultarSaldo.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarSaldo.setText("Consultar Saldo");
        btnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSaldoActionPerformed(evt);
            }
        });

        btnDepositar.setBackground(new java.awt.Color(184, 134, 11));
        btnDepositar.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(0, 0, 0));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnTransferir.setBackground(new java.awt.Color(184, 134, 11));
        btnTransferir.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir.setText("Transferir");
        btnTransferir.setToolTipText("");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnRetirar.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirar.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnPagoServicio.setBackground(new java.awt.Color(184, 134, 11));
        btnPagoServicio.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnPagoServicio.setForeground(new java.awt.Color(0, 0, 0));
        btnPagoServicio.setText("Pago De Servicios");
        btnPagoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoServicioActionPerformed(evt);
            }
        });

        btnVolverMenu.setBackground(new java.awt.Color(184, 134, 11));
        btnVolverMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverMenu.setText("Volver");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        lblBienvenidaMenu.setBackground(new java.awt.Color(212, 175, 55));
        lblBienvenidaMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblBienvenidaMenu.setForeground(new java.awt.Color(212, 175, 55));
        lblBienvenidaMenu.setText("¿Qué podemos hacer por ti hoy?");

        lblFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_registro.jpg"))); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblBienvenidaMenu)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagoServicio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFondoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(lblBienvenidaMenu)
                        .addGap(104, 104, 104)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(btnPagoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblFondoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCards.add(panelMenu, "card4");

        panelTransferir.setBackground(new java.awt.Color(0, 0, 0));

        txtDestinatario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinatarioActionPerformed(evt);
            }
        });

        txtMontoTransferir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtMontoTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTransferirActionPerformed(evt);
            }
        });

        btnConfirmarTransferencia.setBackground(new java.awt.Color(184, 134, 11));
        btnConfirmarTransferencia.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        btnConfirmarTransferencia.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarTransferencia.setText("Confirmar");
        btnConfirmarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTransferenciaActionPerformed(evt);
            }
        });

        btnCancelarTransferencia.setBackground(new java.awt.Color(184, 134, 11));
        btnCancelarTransferencia.setFont(new java.awt.Font("Segoe UI Black", 0, 40)); // NOI18N
        btnCancelarTransferencia.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarTransferencia.setText("Cancelar");
        btnCancelarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTransferenciaActionPerformed(evt);
            }
        });

        lblTransferenciaElectronica.setBackground(new java.awt.Color(212, 175, 55));
        lblTransferenciaElectronica.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblTransferenciaElectronica.setForeground(new java.awt.Color(212, 175, 55));
        lblTransferenciaElectronica.setText("TRANSFERENCIA ELECTRÓNICA");

        lblMontoTransferencia.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblMontoTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        lblMontoTransferencia.setText("MONTO A TRANSFERIR:");

        lblNoDestinatario.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblNoDestinatario.setForeground(new java.awt.Color(255, 255, 255));
        lblNoDestinatario.setText("NÚMERO DEL DESTINATARIO:");

        lblFondoTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_retirar.jpg"))); // NOI18N

        javax.swing.GroupLayout panelTransferirLayout = new javax.swing.GroupLayout(panelTransferir);
        panelTransferir.setLayout(panelTransferirLayout);
        panelTransferirLayout.setHorizontalGroup(
            panelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferirLayout.createSequentialGroup()
                .addGroup(panelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransferenciaElectronica)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoDestinatario)
                    .addComponent(lblMontoTransferencia)
                    .addComponent(txtMontoTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransferirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFondoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1019, Short.MAX_VALUE))
        );
        panelTransferirLayout.setVerticalGroup(
            panelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferirLayout.createSequentialGroup()
                .addComponent(lblTransferenciaElectronica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNoDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMontoTransferencia)
                .addGap(18, 18, 18)
                .addComponent(txtMontoTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(panelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblFondoTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCards.add(panelTransferir, "pantallaTransferir");

        panelRetirar.setBackground(new java.awt.Color(0, 0, 0));

        txtDineroRetir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtDineroRetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDineroRetirActionPerformed(evt);
            }
        });

        btnRetirar50.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirar50.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirar50.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar50.setText("Retirar 50$");
        btnRetirar50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar50ActionPerformed(evt);
            }
        });

        btnRetirar200.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirar200.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirar200.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar200.setText("Retirar 200$");
        btnRetirar200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar200ActionPerformed(evt);
            }
        });

        btnRetirar500.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirar500.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirar500.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar500.setText("Retirar 500$");
        btnRetirar500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar500ActionPerformed(evt);
            }
        });

        btnRetirar101.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirar101.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirar101.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar101.setText("Retirar 100$");
        btnRetirar101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar101ActionPerformed(evt);
            }
        });

        btnRetirarDinero.setBackground(new java.awt.Color(184, 134, 11));
        btnRetirarDinero.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnRetirarDinero.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirarDinero.setText("RETIRAR");
        btnRetirarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarDineroActionPerformed(evt);
            }
        });

        btnVolverRetiro.setBackground(new java.awt.Color(184, 134, 11));
        btnVolverRetiro.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnVolverRetiro.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverRetiro.setText("VOLVER");
        btnVolverRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRetiroActionPerformed(evt);
            }
        });

        lblRetiroDeEfectivo.setBackground(new java.awt.Color(212, 175, 55));
        lblRetiroDeEfectivo.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblRetiroDeEfectivo.setForeground(new java.awt.Color(212, 175, 55));
        lblRetiroDeEfectivo.setText("RETIRO DE EFECTIVO");

        lblDineroRetirar.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblDineroRetirar.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroRetirar.setText("DINERO A RETIRAR:");

        lblRetiroRapido.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblRetiroRapido.setForeground(new java.awt.Color(255, 255, 255));
        lblRetiroRapido.setText("RETIRO RÁPIDO");

        lblSaldoDisponibleRetiro.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblSaldoDisponibleRetiro.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponibleRetiro.setText("Saldo disponible: $[Monto]");

        lblImagenFondoRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_retirar.jpg"))); // NOI18N

        javax.swing.GroupLayout panelRetirarLayout = new javax.swing.GroupLayout(panelRetirar);
        panelRetirar.setLayout(panelRetirarLayout);
        panelRetirarLayout.setHorizontalGroup(
            panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRetirarLayout.createSequentialGroup()
                .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRetiroDeEfectivo)
                    .addComponent(lblDineroRetirar)
                    .addComponent(txtDineroRetir, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoDisponibleRetiro)
                    .addComponent(btnRetirarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRetirarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetiroRapido)
                            .addGroup(panelRetirarLayout.createSequentialGroup()
                                .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRetirar50, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRetirar200, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRetirar500, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRetirar101, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelRetirarLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnVolverRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagenFondoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        panelRetirarLayout.setVerticalGroup(
            panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRetirarLayout.createSequentialGroup()
                .addComponent(lblRetiroDeEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldoDisponibleRetiro)
                .addGap(18, 18, 18)
                .addComponent(lblDineroRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDineroRetir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRetirarDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblRetiroRapido)
                .addGap(18, 18, 18)
                .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar50, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar101, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetirar500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addComponent(btnVolverRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRetirarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImagenFondoRetiro))
        );

        panelCards.add(panelRetirar, "pantallaRetirar");

        panelPagoServicios.setBackground(new java.awt.Color(0, 0, 0));

        lblRetiroDeEfectivo1.setBackground(new java.awt.Color(212, 175, 55));
        lblRetiroDeEfectivo1.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        lblRetiroDeEfectivo1.setForeground(new java.awt.Color(212, 175, 55));
        lblRetiroDeEfectivo1.setText("PAGO DE SERVICIOS");

        lblDineroRetirar1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblDineroRetirar1.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroRetirar1.setText("SERVICIOS DISPONIBLES:");

        cbxTipoServicio.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        cbxTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luz (CFE)", "Agua (SIAPA)", "Internet (Telmex)", "Teléfono " }));

        txtMontoServicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtMontoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoServicioActionPerformed(evt);
            }
        });

        lblDineroRetirar2.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        lblDineroRetirar2.setForeground(new java.awt.Color(255, 255, 255));
        lblDineroRetirar2.setText("MONTO A PAGAR:");

        btnConfirmarPago.setBackground(new java.awt.Color(184, 134, 11));
        btnConfirmarPago.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnConfirmarPago.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarPago.setText("CONFIRMAR");
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });

        btnVolverServicios.setBackground(new java.awt.Color(184, 134, 11));
        btnVolverServicios.setFont(new java.awt.Font("Segoe UI Black", 0, 25)); // NOI18N
        btnVolverServicios.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverServicios.setText("VOLVER");
        btnVolverServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverServiciosActionPerformed(evt);
            }
        });

        lblPagoServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_registro.jpg"))); // NOI18N

        javax.swing.GroupLayout panelPagoServiciosLayout = new javax.swing.GroupLayout(panelPagoServicios);
        panelPagoServicios.setLayout(panelPagoServiciosLayout);
        panelPagoServiciosLayout.setHorizontalGroup(
            panelPagoServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoServiciosLayout.createSequentialGroup()
                .addGroup(panelPagoServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDineroRetirar2)
                    .addComponent(lblDineroRetirar1)
                    .addComponent(cbxTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPagoServiciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPagoServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetiroDeEfectivo1)
                            .addGroup(panelPagoServiciosLayout.createSequentialGroup()
                                .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btnVolverServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPagoServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPagoServiciosLayout.setVerticalGroup(
            panelPagoServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoServiciosLayout.createSequentialGroup()
                .addComponent(lblRetiroDeEfectivo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDineroRetirar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblDineroRetirar2)
                .addGap(18, 18, 18)
                .addComponent(txtMontoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(panelPagoServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 782, Short.MAX_VALUE))
            .addComponent(lblPagoServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCards.add(panelPagoServicios, "pantallaServicios");

        getContentPane().add(panelCards, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        String idABuscar = javax.swing.JOptionPane.showInputDialog(this, "Ingresa tu número de usuario:");

        if (idABuscar != null && !idABuscar.isEmpty()) {
            boolean encontrado = false;
            for (Usuario u : listaUsuarios) {
                if (u.getId().equals(idABuscar)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tu contraseña es: " + u.getPassword());
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
            }
        }
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void btnCrearNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevoActionPerformed

        CardLayout cl = (CardLayout) panelCards.getLayout();

        cl.show(panelCards, "card3");
    }//GEN-LAST:event_btnCrearNuevoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        String idIngresado = txtNombre.getText();
        String passIngresada = txtPassword.getText();

        for (Usuario u : listaUsuarios) {
            if (u.getId().equals(idIngresado) && u.getPassword().equals(passIngresada)) {

                usuarioActual = u;

                lblBienvenidaMenu.setText("¡Hola, " + usuarioActual.getId() + "! ¿Qué haremos hoy?");

                CardLayout cl = (CardLayout) panelCards.getLayout();
                cl.show(panelCards, "card4");
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Número de usuario o contraseña incorrectos.");
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed
        try {

            String nombre = txtRegUsuario.getText().trim();
            String pass = new String(txtRegPass.getPassword());
            String montoTexto = txtRegMonto.getText().trim();

            if (nombre.isEmpty() || pass.isEmpty() || montoTexto.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
                return;
            }

            for (Usuario u : listaUsuarios) {
                if (u.getId().equalsIgnoreCase(nombre)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe.");
                    return;
                }
            }

            double saldoInicial = Double.parseDouble(montoTexto);
            if (saldoInicial < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El saldo no puede ser negativo.");
                return;
            }

            listaUsuarios.add(new Usuario(nombre, pass, saldoInicial));
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!");

            limpiarCamposRegistro();
            CardLayout cl = (CardLayout) panelCards.getLayout();
            cl.show(panelCards, "card2");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El monto debe ser un número válido.");
        }
    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    private void btnVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLoginActionPerformed
        limpiarCamposRegistro();
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "card2");
    }//GEN-LAST:event_btnVolverLoginActionPerformed

    private void txtRegMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegMontoActionPerformed

    private void txtRegUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegUsuarioActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        String respuesta = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el monto a depositar:");

        if (respuesta != null && !respuesta.isEmpty()) {
            try {
                double monto = Double.parseDouble(respuesta);
                if (monto > 0) {
                    usuarioActual.setSaldo(usuarioActual.getSaldo() + monto);
                    javax.swing.JOptionPane.showMessageDialog(this, "Depósito exitoso. Nuevo saldo: $" + usuarioActual.getSaldo());
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser positivo.");
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.");
            }
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "pantallaTransferir");
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnPagoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoServicioActionPerformed
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "pantallaServicios");
    }//GEN-LAST:event_btnPagoServicioActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Deseas cerrar tu sesión?", "Salir", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            usuarioActual = null;
            txtNombre.setText("");
            txtPassword.setText("");

            CardLayout cl = (CardLayout) panelCards.getLayout();
            cl.show(panelCards, "card2");
        }
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
                "Estimado cliente, su saldo actual es:\n$" + usuarioActual.getSaldo(),
                "Consulta de Saldo - BancoMex",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConsultarSaldoActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "pantallaRetirar");
    }

    private void btnRetirar100ActionPerformed(java.awt.event.ActionEvent evt) {
        txtDineroRetir.setText("100");
        btnRetirarDineroActionPerformed(evt);
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void txtDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinatarioActionPerformed

    private void txtMontoTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTransferirActionPerformed

    private void btnConfirmarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTransferenciaActionPerformed
        try {
            String idDestino = txtDestinatario.getText().trim();
            double monto = Double.parseDouble(txtMontoTransferir.getText());
            Usuario receptor = null;

            for (Usuario u : listaUsuarios) {
                if (u.getId().equals(idDestino)) {
                    receptor = u;
                    break;
                }
            }

            if (receptor == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "El destinatario no existe.");
                return;
            }
            if (idDestino.equals(usuarioActual.getId())) {
                javax.swing.JOptionPane.showMessageDialog(this, "No puedes transferirte a ti mismo.");
                return;
            }
            if (usuarioActual.getSaldo() < monto) {
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo insuficiente.");
                return;
            }

            usuarioActual.setSaldo(usuarioActual.getSaldo() - monto);
            receptor.setSaldo(receptor.getSaldo() + monto);

            javax.swing.JOptionPane.showMessageDialog(this, "Transferencia exitosa por $" + monto);

            txtDestinatario.setText("");
            txtMontoTransferir.setText("");
            CardLayout cl = (CardLayout) panelCards.getLayout();
            cl.show(panelCards, "card4");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa un monto válido.");
        }
    }//GEN-LAST:event_btnConfirmarTransferenciaActionPerformed

    private void btnCancelarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTransferenciaActionPerformed
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "card4");
    }//GEN-LAST:event_btnCancelarTransferenciaActionPerformed

    private void txtDineroRetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDineroRetirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDineroRetirActionPerformed

    private void btnRetirar50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar50ActionPerformed
        txtDineroRetir.setText("50");
        btnRetirarDineroActionPerformed(evt);
    }//GEN-LAST:event_btnRetirar50ActionPerformed

    private void btnRetirar200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar200ActionPerformed
        txtDineroRetir.setText("200");
        btnRetirarDineroActionPerformed(evt);
    }//GEN-LAST:event_btnRetirar200ActionPerformed

    private void btnRetirar500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar500ActionPerformed
        txtDineroRetir.setText("500");
        btnRetirarDineroActionPerformed(evt);
    }//GEN-LAST:event_btnRetirar500ActionPerformed

    private void btnRetirarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarDineroActionPerformed
        try {
            double montoARetirar = Double.parseDouble(txtDineroRetir.getText());

            if (montoARetirar <= usuarioActual.getSaldo()) {

                double nuevoSaldo = usuarioActual.getSaldo() - montoARetirar;

                usuarioActual.setSaldo(nuevoSaldo);

                javax.swing.JOptionPane.showMessageDialog(this, "Retiro exitoso. Saldo actual: $" + usuarioActual.getSaldo());

                CardLayout cl = (CardLayout) panelCards.getLayout();
                cl.show(panelCards, "card4");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo insuficiente.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un número válido.");
        }
    }//GEN-LAST:event_btnRetirarDineroActionPerformed

    private void btnVolverRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRetiroActionPerformed
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "card4");
    }//GEN-LAST:event_btnVolverRetiroActionPerformed

    private void btnRetirar101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar101ActionPerformed
        txtDineroRetir.setText("100");
        btnRetirarDineroActionPerformed(evt);
    }//GEN-LAST:event_btnRetirar101ActionPerformed

    private void txtMontoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoServicioActionPerformed

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
        try {

            String servicio = cbxTipoServicio.getSelectedItem().toString();
            double montoAPagar = Double.parseDouble(txtMontoServicio.getText());

            if (montoAPagar <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
                return;
            }

            if (usuarioActual.getSaldo() >= montoAPagar) {

                usuarioActual.setSaldo(usuarioActual.getSaldo() - montoAPagar);

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Pago de " + servicio + " realizado con éxito.\nNuevo saldo: $" + usuarioActual.getSaldo());

                txtMontoServicio.setText("");
                CardLayout cl = (CardLayout) panelCards.getLayout();
                cl.show(panelCards, "card4");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Saldo insuficiente para pagar este servicio.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa un monto numérico válido.");
        }
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    private void btnVolverServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverServiciosActionPerformed
        txtMontoServicio.setText("");
        CardLayout cl = (CardLayout) panelCards.getLayout();
        cl.show(panelCards, "card4");
    }//GEN-LAST:event_btnVolverServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Banco().setVisible(true));
    }

    private void limpiarCamposRegistro() {
        txtRegUsuario.setText("");
        txtRegPass.setText("");
        txtRegMonto.setText("");
    }

    private void setImagenLabel(String ruta, javax.swing.JLabel etiqueta) {
        try {
            java.net.URL imgURL = getClass().getResource(ruta);

            if (imgURL != null) {
                javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(imgURL);
                java.awt.Image imagen = iconoOriginal.getImage();

                int width = etiqueta.getWidth() > 0 ? etiqueta.getWidth() : 1222;
                int height = etiqueta.getHeight() > 0 ? etiqueta.getHeight() : 774;

                java.awt.Image imagenEscalada = imagen.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
                etiqueta.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            } else {
                System.err.println("No se encontró la imagen en: " + ruta);
            }
        } catch (Exception e) {
            System.err.println("Error cargando imagen: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTransferencia;
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnConfirmarTransferencia;
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnCrearNuevo;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPagoServicio;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetirar101;
    private javax.swing.JButton btnRetirar200;
    private javax.swing.JButton btnRetirar50;
    private javax.swing.JButton btnRetirar500;
    private javax.swing.JButton btnRetirarDinero;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVolverLogin;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JButton btnVolverRetiro;
    private javax.swing.JButton btnVolverServicios;
    private javax.swing.JComboBox<String> cbxTipoServicio;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblBienvenidaMenu;
    private javax.swing.JLabel lblDineroRetirar;
    private javax.swing.JLabel lblDineroRetirar1;
    private javax.swing.JLabel lblDineroRetirar2;
    private javax.swing.JLabel lblEtiquetaPass;
    private javax.swing.JLabel lblEtiquetaPass1;
    private javax.swing.JLabel lblEtiquetaUsuario2;
    private javax.swing.JLabel lblFondoMenu;
    private javax.swing.JLabel lblFondoRegistro;
    private javax.swing.JLabel lblFondoTransferencia;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblImagenFondoRetiro;
    private javax.swing.JLabel lblMontoTransferencia;
    private javax.swing.JLabel lblNoDestinatario;
    private javax.swing.JLabel lblPagoServicios;
    private javax.swing.JLabel lblRegMonto;
    private javax.swing.JLabel lblRegNombre;
    private javax.swing.JLabel lblRegPass;
    private javax.swing.JLabel lblRetiroDeEfectivo;
    private javax.swing.JLabel lblRetiroDeEfectivo1;
    private javax.swing.JLabel lblRetiroRapido;
    private javax.swing.JLabel lblSaldoDisponibleRetiro;
    private javax.swing.JLabel lblTituloBanco;
    private javax.swing.JLabel lblTituloRegistro;
    private javax.swing.JLabel lblTransferenciaElectronica;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPagoServicios;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelRetirar;
    private javax.swing.JPanel panelTransferir;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDineroRetir;
    private javax.swing.JTextField txtMontoServicio;
    private javax.swing.JTextField txtMontoTransferir;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRegMonto;
    private javax.swing.JPasswordField txtRegPass;
    private javax.swing.JTextField txtRegUsuario;
    // End of variables declaration//GEN-END:variables
}
